name: CI & CD
on:
  push:
    branches:
      - master
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install packages
        run: yarn
      - name: Build WeChat version
        run: yarn build:weapp
        env:
          NODE_ENV: production
      - name: Get NPM version
        uses: martinbeentjes/npm-get-version-action@master
        id: package-version
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: WeChat-miniapp-${{ steps.package-version.outputs.current-version }}-bundle
          path: ./dist/
      - name: Build HTML 5 version
        run: yarn build:h5
      - name: Deploy HTML 5 version
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
